### ISSUE TITLE
Not support java:6

### ISSUE THREAD

**Issue by Dreampie** [spotify/docker-maven-plugin#274]

**Comment by mattnworb** [comment]
Can you expand on what you are asking for here? This is completely unclear.

**Comment by Dreampie** [comment]
I use java 6,when use plugin to build,get error: some file compile version 51.0, but java 6 is 50.0

**Comment by Dreampie** [comment]
```
Failed to execute goal com.spotify:docker-maven-plugin:0.4.13:build (default-cli) on project resty-example: Execution default-cli of goal com.spotify:docker-maven-plugin:0.4.13:build failed: Unable to load the mojo 'build' in the plugin 'com.spotify:docker-maven-plugin:0.4.13' due to an API incompatibility: org.codehaus.plexus.component.repository.exception.ComponentLookupException: com/spotify/docker/BuildMojo : Unsupported major.minor version 51.0
```

**Comment by mattnworb** [comment]
I am sorry for the inconvenience but I think we are very unlikely to build and release the plugin with Java 6 instead of 7 as we are now. Oracle declared an end of support for Java 6 back in 2013. You are free of course to fork the project and build and release it yourself using a Java 6 VM - there should be few areas of the plugin code that need to be updated for language changes in 7.
